### ISSUE TITLE
Match query results on class granularity

### ISSUE THREAD

**Issue by zgthompson** [Alfwich/ssu_scheduler#5]
If you search Ravi, the courses taught by Ravi show up as expected, but classes of those courses not taught by Ravi also show up. Currently the search finds all classes from any course that has Ravi as a teacher.

Example:

CS242	Discrete Structures for CS	4.00 units
#2845
MW 12:00 PM-01:50 PM	DARW0107	Ravikumar	DIS
#4347
MW 12:00 PM-01:50 PM	STEV2050	Trockel	DIS

**Comment by Alfwich** [comment]
Completed and merged on recent branch 'classes-data-conversion'
