### ISSUE TITLE
An invalid schedule is displayed when there is only one generated schedule

### ISSUE THREAD

**Issue by hallca** [Alfwich/ssu_scheduler#77]
If only one schedule is generated, it is displayed even if it is invalidated with a time conflict. 

Ex:
CS-351 in one slot
JWST-255 in another

**Comment by hallca** [comment]
![screenshot from 2015-04-01 19 53 45](https://cloud.githubusercontent.com/assets/5498313/6956859/d3db19de-d8a8-11e4-8d95-b7aa7924aa65.png)

**Comment by Alfwich** [comment]
Fixed in #77
